FILE_SIZE_DESC = 4
FILE_NAME_DESC = 2
SIGN = b'LANCOM'
SHAKING_SIGN = b'HEYSENDER'
ANSWER_SIGN = b'HEYRECEIVER'
RECEIVER_FINISH_SIGN = b'RFINISH'
BLOCK_COUNT_SIZE = 4
BLOCK_SIZE_SIZE = 4
TAIL_SIZE_SIZE = 8

EACH_BLOCK_SIZE = 8192
RECEIVE_METHOD_LIMIT = 10 * 1024 * 1024
